# Anode Docworker - Cloudflare Worker Configuration
#
# To deploy your own worker:
# 1. Create D1 database: pnpm wrangler d1 create your-database-name
# 2. Update database_id below with the real ID from step 1
# 3. Optionally change the worker name
# 4. Deploy: pnpm wrangler deploy --env production
# 5. Set secrets: pnpm wrangler secret put AUTH_TOKEN --env production

# Default environment (local development)
name = "anode-docworker"
main = "./src/index.ts"
compatibility_date = "2025-05-08"

# Static assets removed - web client now served by Cloudflare Pages

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketServer"]

[[d1_databases]]
binding = "DB"
database_name = "anode-docworker-dev-db"
# Local development uses local SQLite in .wrangler/ - database_id is ignored
database_id = "local"

[vars]
# Environment variables (non-sensitive)
DEPLOYMENT_ENV = "development"
# Worker only serves API endpoints - no web client vars needed

# Production environment
[env.production]
name = "anode-docworker"

[[env.production.durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[env.production.d1_databases]]
binding = "DB"
database_name = "anode-docworker-prototype-db"
database_id = "5339094f-f406-4236-97c3-ada460373f18"

[env.production.vars]
DEPLOYMENT_ENV = "production"
GOOGLE_CLIENT_ID = "94663405566-1go7jlpd2ar9u9urbfirmtjv1bm0tcis.apps.googleusercontent.com"
# Worker only serves API endpoints - web client vars moved to Pages

# Secrets to be set per environment via: pnpm wrangler secret put SECRET_NAME [--env ENV_NAME]
# For local development:
# - AUTH_TOKEN: Set in .env file (AUTH_TOKEN=insecure-token-change-me)
# For production:
# - AUTH_TOKEN: Set via: echo "your-secure-token" | pnpm wrangler secret put AUTH_TOKEN --env production
# Optional for production:
# - GOOGLE_CLIENT_ID: Google OAuth client ID for production authentication
# - GOOGLE_CLIENT_SECRET: Google OAuth client secret (optional, improves validation)
