# Anode Web Client - Cloudflare Pages Configuration
#
# This configures the web client for deployment to Cloudflare Pages
# The sync backend runs on a separate Cloudflare Worker

name = "anode"
pages_build_output_dir = "./dist"
compatibility_date = "2025-06-19"

# Environment variables for production
[vars]
VITE_LIVESTORE_SYNC_URL = "wss://anode-docworker.rgbkrk.workers.dev/api"
VITE_GOOGLE_AUTH_ENABLED = "true"
VITE_GOOGLE_CLIENT_ID = "94663405566-1go7jlpd2ar9u9urbfirmtjv1bm0tcis.apps.googleusercontent.com"
VITE_AUTH_TOKEN = "insecure-token-change-me"

# Preview environment (for development branches)
[env.preview]
[env.preview.vars]
VITE_LIVESTORE_SYNC_URL = "ws://localhost:8787/api"
VITE_GOOGLE_AUTH_ENABLED = "false"
VITE_GOOGLE_CLIENT_ID = "94663405566-1go7jlpd2ar9u9urbfirmtjv1bm0tcis.apps.googleusercontent.com"
VITE_AUTH_TOKEN = "insecure-token-change-me"
